version: "3.3"

services:

  #service 1: definition of mysql database
  db:
    image: library-db
    container_name: library-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3307:3306"
    restart: always

      #service 3: definition of your angular frontend
  library-frontend: #it is just a name, which will be used only in this file.
    image: nejishow/library-frontend:latest #name of the image after dockerfile executes
    container_name: library-frontend #name of the container created from docker image
    ports:
      - "4200:80" #docker containter port with your os port
    restart: always

    depends_on: #define dependencies of this app
    - library-app #dependency name (which is defined with this name 'library-app' in this file earlier)


      #service 3: definition of your spring-boot app
  library-app: #it is just a name, which will be used only in this file.
    image: library #name of the image after dockerfile executes
    container_name: library-app #name of the container created from docker image
    ports:
      - "8080:8080" #docker containter port with your os port
    restart: always

    depends_on: #define dependencies of this app
      - db #dependency name (which is defined with this name 'db' in this file earlier)


#I can use it also
#networks:
 # default:
  #   external:
   #   name: spring